name: Minify and Restructure
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Node.jsのインストール
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: 依存関係のインストール
      run: |
        npm install -g html-minifier-terser
        npm install -g clean-css-cli
        npm install -g terser
    - name: originalフォルダの親フォルダを削除
      run: |
        shopt -s extglob
        rm -rf !(original)
        echo "originalフォルダ以外の親フォルダを削除しました"
    - name: originalフォルダのディレクトリ構成を親フォルダにコピー
      run: |
        find original -type d | sed 's|^original/||' | xargs -I {} mkdir -p {}
        echo "ディレクトリ構造をoriginalから親フォルダにコピーしました"
    - name: originalフォルダのディレクトリ構成をoriginal_tempフォルダにコピー
      run: |
        cp -R original original_temp
        echo "ディレクトリ構造をoriginal_tempフォルダにコピーしました"
    - name: HTMLファイルのミニファイ化
      run: |
        find original -type f -name "*.html" | while read file; do
          output_file="${file/original/original_temp}"
          html-minifier-terser "$file" -o "$output_file" --collapse-whitespace --remove-comments --minify-css true --minify-js true
        done
    - name: CSSファイルのミニファイ化
      run: |
        find original -type f -name "*.css" | while read file; do
          output_file="${file/original/original_temp}"
          cleancss -o "$output_file" "$file"
        done
    - name: JSファイルのミニファイ化
      run: |
        find original -type f -name "*.js" | while read file; do
          output_file="${file/original/original_temp}"
          terser "$file" -o "$output_file"
        done
    - name: original_tempの中身を表示
      run: |
        echo "original_tempフォルダの内容:"
        ls -R original_temp
    - name: original_tempの中身を親フォルダにコピー
      run: |
        cp -R original_temp/* .
        echo "original_tempの中身を親フォルダにコピーしました"
    - name: original_tempフォルダを削除
      run: |
        rm -rf original_temp
        echo "original_tempフォルダを削除しました"
    - name: 変更をコミットしてプッシュ
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m 'originalディレクトリからファイルをミニファイ化および再構築' || echo "コミットする変更はありません"
        git pull --rebase origin main
        git push